
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FSI = 21;
  public static final int Y = 30;
  public static final int FFUN = 29;
  public static final int TIPO = 33;
  public static final int POR = 18;
  public static final int OCT = 4;
  public static final int CCIERRE = 8;
  public static final int LLAMAR = 38;
  public static final int PCIERRE = 6;
  public static final int ENTERO = 48;
  public static final int SI = 20;
  public static final int CIERTO = 50;
  public static final int RESERVA = 40;
  public static final int O = 31;
  public static final int CAP = 7;
  public static final int FMIENTRAS = 25;
  public static final int ENTONCES = 22;
  public static final int HEX = 2;
  public static final int IGUAL = 10;
  public static final int OPCION = 37;
  public static final int FUN = 27;
  public static final int BOOL = 51;
  public static final int MIENTRAS = 24;
  public static final int DIV = 19;
  public static final int CC = 23;
  public static final int DIR = 9;
  public static final int FMULTIOPCION = 42;
  public static final int EOF = 0;
  public static final int MAYOROIGUAL = 14;
  public static final int DISTINCT = 43;
  public static final int error = 1;
  public static final int MENOS = 17;
  public static final int MENOR = 11;
  public static final int ES = 28;
  public static final int PUNTERO = 34;
  public static final int MENOROIGUAL = 13;
  public static final int MAYOR = 12;
  public static final int ENT = 44;
  public static final int PAP = 5;
  public static final int FLECHA = 32;
  public static final int NO = 46;
  public static final int BIN = 3;
  public static final int PUNTO = 15;
  public static final int MULTIOPCION = 41;
  public static final int IDEN = 47;
  public static final int FALSO = 49;
  public static final int TIENE = 35;
  public static final int HACER = 26;
  public static final int LIBERA = 39;
  public static final int CERO = 45;
  public static final int FTIPO = 36;
  public static final int MAS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HEX",
  "BIN",
  "OCT",
  "PAP",
  "PCIERRE",
  "CAP",
  "CCIERRE",
  "DIR",
  "IGUAL",
  "MENOR",
  "MAYOR",
  "MENOROIGUAL",
  "MAYOROIGUAL",
  "PUNTO",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "SI",
  "FSI",
  "ENTONCES",
  "CC",
  "MIENTRAS",
  "FMIENTRAS",
  "HACER",
  "FUN",
  "ES",
  "FFUN",
  "Y",
  "O",
  "FLECHA",
  "TIPO",
  "PUNTERO",
  "TIENE",
  "FTIPO",
  "OPCION",
  "LLAMAR",
  "LIBERA",
  "RESERVA",
  "MULTIOPCION",
  "FMULTIOPCION",
  "DISTINCT",
  "ENT",
  "CERO",
  "NO",
  "IDEN",
  "ENTERO",
  "FALSO",
  "CIERTO",
  "BOOL"
  };
}

